### PR TITLE
feat: Improves http error handling

### PR DESCRIPTION
**Pull request by Darkheir**
This pull requests aims to improve error handling by raising custom exceptions depending on the http return code.

The base exception extends `Exception` so it should be compatible with the current behavior.

### CODE REVIEW

**Comment by Rafiot** [comment]
Looks good, thanks!

**Comment by Darkheir** [comment]
Thank you for the quick merge!

Do you plan on releasing a new version in the python package index soon ?

**Comment by Rafiot** [comment]
Good point. I'll try to do that later today.

**Comment by Rafiot** [comment]
Here it is! https://pypi.org/project/pypdns/

**Comment by Darkheir** [comment]
Awesome! Many thanks!

**Pull request merged**
